// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ__ROAInMnpTtiQUajYDFtU4eclGP-F8',
    appId: '1:151910861304:web:b32d795573ae6c56066e0d',
    messagingSenderId: '151910861304',
    projectId: 'parking-e40c3',
    authDomain: 'parking-e40c3.firebaseapp.com',
    storageBucket: 'parking-e40c3.firebasestorage.app',
    measurementId: 'G-SYMSQG5KF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYPsoySaEzHv_2TKK5164FWLFCPFyz2lg',
    appId: '1:151910861304:android:b05da2f9c6823dd2066e0d',
    messagingSenderId: '151910861304',
    projectId: 'parking-e40c3',
    storageBucket: 'parking-e40c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-spDga1FDizNF1Y2wRE2OvwrMoLLq4NY',
    appId: '1:151910861304:ios:8b0ab880e8d51fc6066e0d',
    messagingSenderId: '151910861304',
    projectId: 'parking-e40c3',
    storageBucket: 'parking-e40c3.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-spDga1FDizNF1Y2wRE2OvwrMoLLq4NY',
    appId: '1:151910861304:ios:8b0ab880e8d51fc6066e0d',
    messagingSenderId: '151910861304',
    projectId: 'parking-e40c3',
    storageBucket: 'parking-e40c3.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ__ROAInMnpTtiQUajYDFtU4eclGP-F8',
    appId: '1:151910861304:web:39e693cfdc0d36f2066e0d',
    messagingSenderId: '151910861304',
    projectId: 'parking-e40c3',
    authDomain: 'parking-e40c3.firebaseapp.com',
    storageBucket: 'parking-e40c3.firebasestorage.app',
    measurementId: 'G-ELT9SPDDBH',
  );

}